apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ include "queen-califia.ns" . }}
  labels:
{{ include "queen-califia.labels" . | indent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
  selector:
    app: qc-api
    {{- include "queen-califia.selectorLabels" . | nindent 4 }}
