{{- if .Values.config.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
  namespace: {{ include "queen-califia.ns" . }}
  labels:
{{ include "queen-califia.labels" . | indent 4 }}
data:
{{- range $k, $v := .Values.api.env }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
