apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - redis.yaml
  - api.yaml
  - worker.yaml
  - frontend.yaml
  - ingress.yaml
  - cert-manager/clusterissuer-staging.yaml
  - cert-manager/clusterissuer-prod.yaml
  - network-policies/zero-trust.yaml
